inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snipets from READMEs.
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - '**/*.gemspec'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - 'app/views/api/**/*.json.jbuilder'
    - 'config/initializers/simple_form.rb'
    - 'config/unicorn.rb'
    - 'spec/rails_helper.rb'
    - 'lib/tasks/brakeman.rake'
    - 'lib/tasks/elasticsearch.rake'
    - 'spec/dummy/db/**/*'
    - 'spec/spec_helper.rb'


Style/OptionalBooleanParameter:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Rake/MethodDefinitionInTask:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
Style/FormatString:
  Enabled: false
Rails/SaveBang:
  Enabled: false

# Use Weirich style
Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - before
    - let
    - let!
    - subject
    - watch
    - expect

Style/SymbolArray:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'spec/factories/**/*'

# You can't use attr_reader to define a foo? method from @foo.
Style/TrivialAccessors:
  AllowPredicates: true

# Don't worry about long methods in specs.
Metrics/MethodLength:
  Max: 10
  Exclude:
    - 'spec/**/*'
    - 'app/helpers/form_elements_helper.rb'
    - 'app/metrics/**/*' # Some very long SQL based methods there.

# Enforce single quotes everywhere except in specs (because there's a lot of
# human text with apostrophes in spec names, and using double quotes for all
# of those is more consistent. There shouldn't be much human-readable text in
# the application code: that is better moved to the locale files.
Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'spec/**/*'

# Prefer sensible naming to comments everywhere.
Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

# Would enforce do_y if x over if x / do y / end. As with GuardClause above,
# this enforces code organisation that doesn't necesarily make things clearer.
Style/IfUnlessModifier:
  Enabled: false

# Don't allow safe assignment in conditions.
Lint/AssignmentInCondition:
  AllowSafeAssignment: false

# Just a preference to use %w[] over %w()
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'
    '%': '{}'

# This encourages bad style IMHO
Rails/Delegate:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Performance/CompareWithBlock:
  Enabled: false

Performance/RangeInclude:
  Enabled: false

Performance/TimesMap:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Max: 48

RSpec/HookArgument:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 27

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/ApplicationJob:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SignalException:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false

# Below here are failing GovUk styles
Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false
