AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snipets from READMEs.
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - '**/*.gemspec'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - 'config/initializers/simple_form.rb'
    - 'config/unicorn.rb'
    - 'spec/rails_helper.rb'
    - 'lib/tasks/brakeman.rake'
    - 'lib/tasks/elasticsearch.rake'
    - 'spec/dummy/db/**/*'
  RunRailsCops: true

# private/protected/public
Style/AccessModifierIndentation:
  EnforcedStyle: outdent

# Just indent parameters by two spaces. It's less volatile if methods change,
# and there's less busy work lining things up.
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AsciiComments:
  Enabled: false

# Use Weirich style
Style/BlockDelimiters:
  EnforcedStyle: semantic

# Allow ===. It's useful.
Style/CaseEquality:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    inject: 'inject'
    reduce: 'inject'

# Chain methods with trailing dots.
Style/DotPosition:
  EnforcedStyle: trailing

# The holidays file has extra spaces for ease of reading and comparison
Style/ExtraSpacing:
  Exclude:
    - 'config/initializers/holidays.rb'

# Percent-formatting and hash interpolation both have their place. Don't
# enforce any particular one.
Style/FormatString:
  Enabled: false

# It's not really clearer to replace every if with a return if.
Style/GuardClause:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'spec/factories/**/*'

# You can't use attr_reader to define a foo? method from @foo.
Style/TrivialAccessors:
  AllowPredicates: true

Metrics/LineLength:
  Max: 80
  Exclude:
    - 'spec/**/*'

# Don't worry about long methods in specs.
Metrics/MethodLength:
  Max: 10
  Exclude:
    - 'spec/**/*'
    - 'app/helpers/form_elements_helper.rb'

# Don't worry about the complexity of spec methods
Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

# Enforce single quotes everywhere except in specs (because there's a lot of
# human text with apostrophes in spec names, and using double quotes for all
# of those is more consistent. There shouldn't be much human-readable text in
# the application code: that is better moved to the locale files.
Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'spec/**/*'

# Prefer sensible naming to comments everywhere.
Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

# Would enforce do_y if x over if x / do y / end. As with GuardClause above,
# this enforces code organisation that doesn't necesarily make things clearer.
IfUnlessModifier:
  Enabled: false

# Don't allow safe assignment in conditions.
Lint/AssignmentInCondition:
  AllowSafeAssignment: false

# Just a preference to use %w[] over %w()
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'
    '%': '{}'

ClassAndModuleChildren:
  Enabled: false

# This encourages bad style IMHO
Rails/Delegate:
  Enabled: false

require: rubocop-rspec
