version: 0.2

phases:
  pre_build:
    commands:
      - bash -c "$(curl -fsSL https://gist.githubusercontent.com/lukaszraczylo/2c904d43cf5c78aaf5aed3f18a66a7d6/raw/6242fb4cd60847ae1ed2890c381d97d206a40c90/codebuild)"
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region eu-west-1 --no-include-email)
      - BASENAME_REPO=$(basename $CODEBUILD_SOURCE_REPO_URL)
      - echo $BASENAME_REPO
      - REPOSITORY_URI=880656497252.dkr.ecr.eu-west-1.amazonaws.com/${BASENAME_REPO%.*}
      - echo $REPOSITORY_URI
      - IMAGE_TAG=$(git rev-parse --short HEAD)
      - echo $IMAGE_TAG
      - IMAGE_BRANCH=$CODEBUILD_GIT_BRANCH
      - echo $IMAGE_BRANCH

  # build:
  #   commands:
  #     - echo Build started on `date`
  #     - echo Building the Docker image...
  #     - docker build -t $REPOSITORY_URI:latest .
  #     - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_BRANCH.$IMAGE_TAG
  #     - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_BRANCH.latest
  # post_build:
  #   commands:
  #     - echo Build completed on `date`
  #     - echo Pushing the Docker images...
  #     - docker push $REPOSITORY_URI:$IMAGE_BRANCH.$IMAGE_TAG
  #     - docker push $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_BRANCH.latest
