source 'https://rubygems.org'
ruby '2.3.0'

gem 'rails', '~> 4.2.3'

gem 'govuk_frontend_toolkit', '2.0.1'
gem 'high_voltage'
gem 'http_accept_language'
gem 'jbuilder'
gem 'kramdown'
gem 'logstasher'
gem 'moj_template', '0.21.0'
gem 'netaddr'
gem 'pg'
gem 'premailer-rails'
gem 'puma'
gem 'sass-rails', '~> 5.0'
gem 'sendgrid_toolkit'
gem 'sidekiq'
gem 'sinatra'
gem 'state_machines-activerecord'
gem 'string_scrubber'
gem 'uglifier', '>= 1.3.0'
gem 'uri_template'
gem 'virtus'
gem 'zendesk_api'

group :development, :test do
  gem 'brakeman'
  gem 'byebug'
  gem 'parser', '~> 2.3.0.pre.6'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 3.0'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'shoulda-matchers'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'ffaker'
  gem 'fuubar'
  gem 'launchy'
  gem 'phantomjs', require: 'phantomjs/poltergeist'
  gem 'poltergeist'
  gem 'simplecov'
  gem 'simplecov-rcov'
  gem 'webmock'
end
