# The dashboard trial enforces the use of the prison dashboard to process visits
# and switches off the prison emails.
Rails.configuration.dashboard_trial = [
  'Bedford',
  'Belmarsh',
  'Brixton',
  'Bure',
  'Cardiff',
  'Chelmsford',
  'Chelmsford',
  'Coldingley',
  'Downview',
  'Feltham',
  'Foston Hall',
  'Gartree',
  'Glen Parva',
  'High Down',
  'Highpoint',
  'Hollesley Bay Open',
  'Leicester',
  'Lincoln',
  'Littlehey',
  'Long Lartin',
  'North Sea Camp',
  'Norwich',
  'Nottingham',
  'Onley',
  'Pentonville',
  'Send',
  'Stocken',
  'Sudbury',
  'Swansea',
  'The Mount',
  'Usk',
  'Wandsworth',
  'Warren Hill',
  'Whatton',
  'Wormwood Scrubs'
]
