# The dashboard trial enforces the use of the prison dashboard to process visits
# and switches off the prison emails.
Rails.configuration.dashboard_trial = [
  'Bedford',
  'Belmarsh',
  'Brixton',
  'Bure',
  'Cardiff',
  'Chelmsford',
  'Chelmsford',
  'Coldingley',
  'Cookham Wood',
  'Deerbolt',
  'Downview',
  'Durham',
  'East Sutton Park',
  'Elmley',
  'Feltham',
  'Ford',
  'Foston Hall',
  'Frankland',
  'Gartree',
  'Glen Parva',
  'Hatfield Open',
  'High Down',
  'Highpoint',
  'Hollesley Bay Open',
  'Holme House',
  'Hull',
  'Humber',
  'Leeds',
  'Leicester',
  'Lincoln',
  'Lindholme',
  'Littlehey',
  'Long Lartin',
  'Low Newton',
  'Maidstone',
  'Moorland Closed',
  'New Hall',
  'North Sea Camp',
  'Norwich',
  'Nottingham',
  'Onley',
  'Pentonville',
  'Rochester',
  'Send',
  'Standford Hill',
  'Stocken',
  'Sudbury',
  'Swaleside',
  'Swansea',
  'The Mount',
  'Usk',
  'Wakefield',
  'Wandsworth',
  'Warren Hill',
  'Wetherby',
  'Whatton',
  'Wormwood Scrubs'
]
