# The dashboard trial enforces the use of the prison dashboard to process visits
# and switches off the prison emails.
Rails.configuration.dashboard_trial = [
  'Askham Grange',
  'Aylesbury',
  'Bedford',
  'Belmarsh',
  'Brixton',
  'Buckley Hall',
  'Bullingdon',
  'Bure',
  'Cardiff',
  'Chelmsford',
  'Coldingley',
  'Cookham Wood',
  'Deerbolt',
  'Downview',
  'Durham',
  'East Sutton Park',
  'Elmley',
  'Feltham',
  'Ford',
  'Foston Hall',
  'Frankland',
  'Full Sutton',
  'Garth',
  'Gartree',
  'Glen Parva',
  'Grendon',
  'Hatfield Open',
  'Haverigg',
  'High Down',
  'Highpoint',
  'Hindley',
  'Hollesley Bay Open',
  'Holme House',
  'Hull',
  'Humber',
  'Huntercombe',
  'Isle of Wight - Albany',
  'Isle of Wight - Parkhurst',
  'Kennet',
  'Kirkham',
  'Lancaster Farms',
  'Leeds',
  'Leicester',
  'Lewes',
  'Lincoln',
  'Lindholme',
  'Littlehey',
  'Liverpool',
  'Long Lartin',
  'Low Newton',
  'Maidstone',
  'Moorland Closed',
  'New Hall',
  'North Sea Camp',
  'Norwich',
  'Nottingham',
  'Onley',
  'Pentonville',
  'Preston',
  'Ranby',
  'Risley',
  'Rochester',
  'Send',
  'Spring Hill',
  'Standford Hill',
  'Stocken',
  'Styal',
  'Sudbury',
  'Swaleside',
  'Swansea',
  'The Mount',
  'Thorn Cross',
  'Usk',
  'Wakefield',
  'Wandsworth',
  'Warren Hill',
  'Wealstun',
  'Wetherby',
  'Whatton',
  'Winchester',
  'Woodhill',
  'Wormwood Scrubs',
  'Wymott'
]
