Dir[Rails.root.join('lib/types', '*.rb')].each do |file| require file end

ActiveModel::Type.register(:accessible_date,                 AccessibleDateType)
ActiveModel::Type.register(:api_slot_list,                   ApiSlotListType)
ActiveModel::Type.register(:availability_visit_list,         AvailabilityVisitListType)
ActiveModel::Type.register(:concrete_slot,                   ConcreteSlotType)
ActiveModel::Type.register(:concrete_slot_list,              ConcreteSlotListType)
ActiveModel::Type.register(:contacts_enumerable,             ContactsEnumerableType)
ActiveModel::Type.register(:contact_gender,                  ContactGenderType)
ActiveModel::Type.register(:contact_relationship,            ContactRelationshipType)
ActiveModel::Type.register(:contact_type,                    ContactTypeType)
ActiveModel::Type.register(:date_list,                       DateListType)
ActiveModel::Type.register(:housing_location,                HousingLocationType)
ActiveModel::Type.register(:level_list,                      LevelListType)
ActiveModel::Type.register(:nomis_prisoner,                  NomisPrisonerType)
ActiveModel::Type.register(:normalised_concrete_slot,        NormalisedConcreteSlotType)
ActiveModel::Type.register(
  :prisoner_date_availability_list, PrisonerDateAvailabilityListType)
ActiveModel::Type.register(:prisoner_number,                 PrisonerNumberType)
ActiveRecord::Type.register(:prisoner_number,                PrisonerNumberType)
ActiveModel::Type.register(:restriction,                     RestrictionType)
ActiveModel::Type.register(:restriction_type,                RestrictionTypeType)
ActiveModel::Type.register(:restriction_list,                RestrictionListType)
ActiveModel::Type.register(:visitor,                         VisitorType)
ActiveModel::Type.register(:visitor_list,                    VisitorListType)
ActiveModel::Type.register(:visit_order,                     VisitOrderType)
