{
 "title": "Prison Visits",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, namespace)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage STAFF",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{namespace='$namespace',container_name='prison-visits-booking-staff'})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='$namespace',container='prison-visits-booking-staff'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='$namespace',container='prison-visits-booking-staff'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "Memory usage STAFF Sidekiq",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{namespace='$namespace',container_name='prison-visits-booking-staff-sidekiq'})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='$namespace',container='prison-visits-booking-staff-sidekiq'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='$namespace',container='prison-visits-booking-staff-sidekiq'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "Memory usage PUBLIC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{namespace='$namespace',container_name='prison-visits-public'})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='$namespace',container='prison-visits-public'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='$namespace',container='prison-visits-public'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  }
 ]
}