apiVersion: batch/v1
kind: Job
metadata:
  name: pvb-staff-migration-dev
  labels:
    app: pvb-staff-migration-dev
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - name: prison-visits-staff-migration
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/prison-visits-booking/prison-visits-staff:latest
          imagePullPolicy: Always
          command: ['sh', '-c', 'sleep 5 && bundle exec rails db:migrate && bundle exec rails db:seed']
          envFrom:
            - configMapRef:
                name: shared-environment
            - secretRef:
                name: secrets
          env:
            - name: "DISABLE_PROMETHEUS_METRICS"
              value: "true"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prison-visits-rds-instance-output
                  key: url
          resources:
            limits:
              memory: "1Gi"
              cpu: "50m"
            requests:
              memory: "1Gi"
              cpu: "30m"
      restartPolicy: Never
  backoffLimit: 4
