apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prison-visits-booking-staff
  namespace: prison-visits-booking-dev
spec:
  selector:
    matchLabels:
      app: prison-visits-booking-staff
  namespaceSelector:
    matchNames:
    - prison-visits-booking-staff-development
  endpoints:
  - port: metrics
    interval: 15s
 