apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-environment
data:
  PRISON_API_HOST: "https://api-preprod.prison.service.justice.gov.uk"
  NOMIS_OAUTH_HOST: "https://sign-in-dev.hmpps.service.justice.gov.uk"
  NOMIS_OAUTH_PUBLIC_KEY: "zcx7Ybw2BAWv7SsEIUGPiyJSIDgtqBx19Twm7uI3TX5zRcrZlUxcEmPJGUgy-D2JIhVlqmeqwGV2CNOqZBgGj8eJGA59iITze8dmRJNIc7l6lDJg9DNJVOiLqUlZFDCIqzeI63oq6uhccg5DPiTNqOGZc8upN-w5dZrNv-2GLgxK2petMU_BhYeWf3KvYIO16v1uvnFOGO13HoWu5BtdSt_TgclFhVLEdGw7XbiYHnNZIdhwaNQiYgmXmjZVdMyCPDMo10LkV1p3Uy15pMMxUpslJaO06VHarmcvVc3exx96ZGN16Oe8efhxnQvhswFkmyXOnlHZ-4252rGpyJLolw"
  NOMIS_STAFF_SLOT_AVAILABILITY_ENABLED: "true"
  PUBLIC_SERVICE_URL: "https://prison-visits-public-dev.apps.live.cloud-platform.service.justice.gov.uk"
  PVB_TEAM_EMAIL: "pvb-team@digital.justice.gov.uk"
  RACK_ENV: "development"
  RAILS_SERVE_STATIC_FILES: "true"
  REMOVE_LOAD_TEST_DATA: "true"
  SENTRY_CURRENT_ENV: "development"
  STAFF_SERVICE_URL: "https://prison-visits-booking-staff-dev.apps.live.cloud-platform.service.justice.gov.uk"
  SMTP_DOMAIN: "mailtrap.io"
  SMTP_PORT: "465"
  SMTP_HOSTNAME: "smtp.mailtrap.io"
  WEB_CONCURRENCY: "5"
  ZENDESK_URL: "https://ministryofjustice.zendesk.com/api/v2"
  ZENDESK_USERNAME: "pvb-technical-support+zendesk@digital.justice.gov.uk"
  STAFF_PRISONS_WITH_SLOT_AVAILABILITY: >
    Bedford,
    Feltham (Young People 15-18 only),
    Feltham (Young Adults 18-21 only),
    Hull,
    Medway Secure Training Centre,
    Nottingham,
    Swaleside,
    Whitemoor,
  PUBLIC_PRISONS_WITH_SLOT_AVAILABILITY: >
    Bedford,
    Feltham (Young People 15-18 only),
    Feltham (Young Adults 18-21 only),
    Hull,
    Medway Secure Training Centre,
    Nottingham,
    Swaleside,
    Whitemoor,
