apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-environment
data:
  PRISON_API_HOST: "https://prison-api-dev.prison.service.justice.gov.uk"
  NOMIS_OAUTH_HOST: "https://sign-in-dev.hmpps.service.justice.gov.uk"
  KUBERNETES_DEPLOYMENT: "true"
  NOMIS_OAUTH_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6Y3g3WWJ3MkJBV3Y3U3NFSVVHUAppeUpTSURndHFCeDE5VHdtN3VJM1RYNXpSY3JabFV4Y0VtUEpHVWd5K0QySkloVmxxbWVxd0dWMkNOT3FaQmdHCmo4ZUpHQTU5aUlUemU4ZG1SSk5JYzdsNmxESmc5RE5KVk9pTHFVbFpGRENJcXplSTYzb3E2dWhjY2c1RFBpVE4KcU9HWmM4dXBOK3c1ZFpyTnYrMkdMZ3hLMnBldE1VL0JoWWVXZjNLdllJTzE2djF1dm5GT0dPMTNIb1d1NUJ0ZApTdC9UZ2NsRmhWTEVkR3c3WGJpWUhuTlpJZGh3YU5RaVlnbVhtalpWZE15Q1BETW8xMExrVjFwM1V5MTVwTU14ClVwc2xKYU8wNlZIYXJtY3ZWYzNleHg5NlpHTjE2T2U4ZWZoeG5Rdmhzd0ZrbXlYT25sSForNDI1MnJHcHlKTG8KbHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
  NOMIS_STAFF_SLOT_AVAILABILITY_ENABLED: "true"
  PUBLIC_SERVICE_URL: "https://prison-visits-public-dev.apps.live.cloud-platform.service.justice.gov.uk"
  PVB_TEAM_EMAIL: "pvb-team@digital.justice.gov.uk"
  RACK_ENV: "production"
  RAILS_SERVE_STATIC_FILES: "true"
  REMOVE_LOAD_TEST_DATA: "true"
  SENTRY_CURRENT_ENV: "development"
  STAFF_SERVICE_URL: "https://prison-visits-booking-staff-dev.apps.live.cloud-platform.service.justice.gov.uk"
  SMTP_DOMAIN: "mailtrap.io"
  SMTP_PORT: "465"
  SMTP_HOSTNAME: "smtp.mailtrap.io"
  WEB_CONCURRENCY: "5"
  ZENDESK_URL: "https://ministryofjustice.zendesk.com/api/v2"
  ZENDESK_USERNAME: "pvb-technical-support+zendesk@digital.justice.gov.uk"
  STAFF_PRISONS_WITH_SLOT_AVAILABILITY: >
    Bedford,
    Feltham (Young People 15-18 only),
    Feltham (Young Adults 18-21 only),
    High Down,
    Hull,
    Medway Secure Training Centre,
    North Sea Camp,
    Nottingham,
    Swaleside,
    Whitemoor,
  PUBLIC_PRISONS_WITH_SLOT_AVAILABILITY: >
    Bedford,
    Feltham (Young People 15-18 only),
    Feltham (Young Adults 18-21 only),
    High Down,
    Hull,
    Medway Secure Training Centre,
    North Sea Camp,
    Nottingham,
    Swaleside,
    Whitemoor,
