apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-environment
data:
  PRISON_API_HOST: "https://api.prison.service.justice.gov.uk"
  NOMIS_OAUTH_HOST: "https://sign-in.hmpps.service.justice.gov.uk"
  KUBERNETES_DEPLOYMENT: "true"
  MOJSSO_URL: "https://signon.service.justice.gov.uk"
  NOMIS_STAFF_SLOT_AVAILABILITY_ENABLED: "true"
  PUBLIC_SERVICE_URL: "https://prisonvisits.service.gov.uk"
  PVB_TEAM_EMAIL: "pvb-team@digital.justice.gov.uk"
  RACK_ENV: "production"
  RAILS_SERVE_STATIC_FILES: "true"
  REMOVE_LOAD_TEST_DATA: "false"
  SENTRY_CURRENT_ENV: "production"
  STAFF_SERVICE_URL: "https://staff.prisonvisits.service.justice.gov.uk"
  SMTP_DOMAIN: "email.prisonvisits.service.gov.uk"
  WEB_CONCURRENCY: "5"
  ZENDESK_URL: "https://ministryofjustice.zendesk.com/api/v2"
  ZENDESK_USERNAME: "pvb-technical-support+zendesk@digital.justice.gov.uk"
  STAFF_PRISONS_WITH_SLOT_AVAILABILITY: >
    Bedford,
    Feltham (Young People 15-18 only),
    Feltham (Young Adults 18-21 only),
    High Down,
    Hull,
    Medway Secure Training Centre,
    Nottingham,
    Swaleside,
    Whitemoor,
  PUBLIC_PRISONS_WITH_SLOT_AVAILABILITY: >
    Bedford,
    Feltham (Young People 15-18 only),
    Feltham (Young Adults 18-21 only),
    High Down,
    Hull,
    Medway Secure Training Centre,
    Nottingham,
    Swaleside,
    Whitemoor,
