kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata: 
  name: allow-prometheus-scraping
  namespace: prison-visits-booking-staging
spec:
  podSelector:
    matchLabels: 
      app: prison-visits-booking-staff-staging
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: 
        matchLabels: 
          component: monitoring
