apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-environment
data:
  KUBERNETES_DEPLOYMENT: "true"
  MOJSSO_URL: "https://signon.service.justice.gov.uk"
  NOMIS_API_HOST: "https://gateway.preprod.nomis-api.service.hmpps.dsd.io/"
  PUBLIC_SERVICE_URL: "https://prison-visits-public-staging.apps.live-1.cloud-platform.service.justice.gov.uk"
  PVB_TEAM_EMAIL: "pvb-team@digital.justice.gov.uk"
  RACK_ENV: "production"
  RAILS_SERVE_STATIC_FILES: "true"
  REMOVE_LOAD_TEST_DATA: "true"
  STAFF_SERVICE_URL: "https://prison-visits-booking-staff-staging.apps.live-1.cloud-platform.service.justice.gov.uk"
  SMTP_DOMAIN: "mailtrap.io"
  SMTP_PORT: "465"
  SMTP_HOSTNAME: "smtp.mailtrap.io"
  WEB_CONCURRENCY: "5"
  ZENDESK_URL: "https://ministryofjustice.zendesk.com/api/v2"
  ZENDESK_USERNAME: "pvb-technical-support+zendesk@digital.justice.gov.uk"
  STAFF_PRISONS_WITH_SLOT_AVAILABILITY: >
    Askham Grange,
    Aylesbury,
    Bedford,
    Brinsford,
    Buckley Hall,
    Bure,
    Cardiff,
    Channings Wood,
    Chelmsford,
    Coldingley,
    Cookham Wood,
    Dartmoor,
    Deerbolt,
    Downview,
    Drake Hall,
    Durham,
    East Sutton Park,
    Eastwood Park,
    Elmley,
    Erlestoke,
    Exeter,
    Featherstone,
    Feltham (Young People 15-18 only),
    Feltham (Young Adults 18-21 only),
    Ford,
    Foston Hall,
    Frankland,
    Full Sutton,
    Garth,
    Gartree,
    Grendon,
    Guys Marsh,
    Hatfield Open,
    Haverigg,
    Hewell,
    High Down,
    Highpoint South,
    Hindley,
    Holme House,
    Hollesley Bay Open,
    Hull,
    Humber,
    Kirkham,
    Lancaster Farms,
    Leicester,
    Leyhill,
    Lincoln,
    Lindholme,
    Liverpool Social Visits,
    Low Newton,
    Maidstone,
    Medway Secure Training Centre,
    Moorland Closed,
    North Sea Camp,
    Nottingham,
    Pentonville,
    Ranby,
    Rochester,
    Send,
    Stocken,
    Stoke Heath,
    Styal,
    Sudbury,
    Swaleside,
    Swinfen Hall,
    The Mount,
    Thorn Cross,
    Usk,
    Wakefield,
    Wandsworth,
    Warren Hill,
    Wayland,
    Wealstun,
    Werrington,
    Wetherby,
    Whatton,
    Whitemoor,
    Winchester (Convicted only),
    Winchester (Remand only),
    Woodhill,
    Wormwood Scrubs
  PUBLIC_PRISONS_WITH_SLOT_AVAILABILITY: >
    Askham Grange,
    Aylesbury,
    Bedford,
    Buckley Hall,
    Bure,
    Cardiff,
    Channings Wood,
    Chelmsford,
    Coldingley,
    Cookham Wood,
    Dartmoor,
    Deerbolt,
    Downview,
    Drake Hall,
    Durham,
    East Sutton Park,
    Eastwood Park,
    Elmley,
    Erlestoke,
    Exeter,
    Featherstone,
    Feltham (Young People 15-18 only),
    Feltham (Young Adults 18-21 only),
    Ford,
    Foston Hall,
    Frankland,
    Full Sutton,
    Garth,
    Gartree,
    Grendon,
    Guys Marsh,
    Hatfield Open,
    Haverigg,
    Hewell,
    High Down,
    Highpoint South,
    Hindley,
    Hollesley Bay,
    Holme House,
    Hull,
    Humber,
    Kirkham,
    Lancaster Farms,
    Leicester,
    Leyhill,
    Lincoln,
    Lindholme,
    Liverpool Social Visits,
    Low Newton,
    Maidstone,
    Medway Secure Training Centre,
    Moorland Closed,
    Nottingham,
    Pentonville,
    Ranby,
    Send,
    Stocken,
    Stoke Heath,
    Styal,
    Sudbury,
    Swaleside,
    Usk,
    Wakefield,
    Wandsworth,
    Warren Hill,
    Wayland,
    Wealstun,
    Werrington,
    Whitemoor,
    Winchester (Convicted only),
    Wormwood Scrubs
