apiVersion: batch/v1
kind: CronJob
metadata:
  name: anonymise-data
spec:
  {{- if or (eq .Values.environment.name "dev") (eq .Values.environment.name "staging") }}
  schedule: "0 9 * * *"
  {{- end }}
  {{- if (eq .Values.environment.name "production") }}
  schedule: "0 0 * * *"
  {{- end }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: prison-visits-booking-staff-anonymise-data
            image: "{{ index .Values "generic-service" "image" "repository" }}:{{ index .Values "generic-service" "image" "tag" | default .Chart.AppVersion }}"
            imagePullPolicy: IfNotPresent
            command: ['sh', '-c', "bundle exec rake anonymise:remove_old_personal_information"]
            envFrom:
              - configMapRef:
                  name: shared-environment
              - secretRef:
                  name: secrets
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: prison-visits-rds-instance-output
                    key: url
          restartPolicy: OnFailure
