apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "prison-visits-2.fullname" . }}-delete-load-test-data
  labels:
  {{- include "prison-visits-2.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: {{ .Values.deleteLoadTestData.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - sh
            - -c
            - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
            - bundle exec rake load_test_data:delete[Load,Test]
            env:
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
            envFrom:
            - configMapRef:
                name: {{ include "prison-visits-2.fullname" . }}-shared-environment
            - secretRef:
                name: secrets
            image: {{ .Values.deleteLoadTestData.prisonVisitsBookingStaffLoadTestDataDelete.image.repository
              }}:{{ .Values.deleteLoadTestData.prisonVisitsBookingStaffLoadTestDataDelete.image.tag
              | default .Chart.AppVersion }}
            imagePullPolicy: {{ .Values.deleteLoadTestData.prisonVisitsBookingStaffLoadTestDataDelete.imagePullPolicy
              }}
            name: prison-visits-booking-staff-load-test-data-delete
            resources: {}
          restartPolicy: OnFailure
  schedule: {{ .Values.deleteLoadTestData.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.deleteLoadTestData.successfulJobsHistoryLimit
    }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "prison-visits-2.fullname" . }}-anonymise-data
  labels:
  {{- include "prison-visits-2.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: {{ .Values.anonymiseData.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - sh
            - -c
            - bundle exec rake anonymise:remove_old_personal_information
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: prison-visits-rds-instance-output
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
            envFrom:
            - configMapRef:
                name: {{ include "prison-visits-2.fullname" . }}-shared-environment
            - secretRef:
                name: secrets
            image: {{ .Values.anonymiseData.prisonVisitsBookingStaffAnonymiseData.image.repository
              }}:{{ .Values.anonymiseData.prisonVisitsBookingStaffAnonymiseData.image.tag
              | default .Chart.AppVersion }}
            imagePullPolicy: {{ .Values.anonymiseData.prisonVisitsBookingStaffAnonymiseData.imagePullPolicy
              }}
            name: prison-visits-booking-staff-anonymise-data
            resources: {}
          restartPolicy: OnFailure
  schedule: {{ .Values.anonymiseData.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.anonymiseData.successfulJobsHistoryLimit
    }}