{{- $genericService := (index .Values "generic-service") | default (dict) }}
{{- $genericServiceEnv := (index $genericService "env") | default (dict) }}
{{- $environmentName := (index $genericServiceEnv "ENVIRONMENT_NAME") | default "" }}
{{- if or (eq $environmentName "dev") (eq $environmentName "preprod") }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-load-test-data
spec:
  schedule: "0 10 * * 1-5"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: prison-visits-booking-staff-load-test-data-delete
            image: "{{ index .Values "generic-service" "image" "repository" }}:{{ index .Values "generic-service" "image" "tag" | default .Chart.AppVersion }}"
            imagePullPolicy: IfNotPresent
            command: ['sh', '-c', "DISABLE_DATABASE_ENVIRONMENT_CHECK=1", "bundle exec rake load_test_data:delete['Load','Test']"]
            envFrom:
              - configMapRef:
                  name: shared-environment
              - secretRef:
                  name: secrets
          restartPolicy: OnFailure
---
{{- end }}
