apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prison-visits-2.fullname" . }}-prison-visits-booking-staff
  labels:
    app: prison-visits-booking-staff
  {{- include "prison-visits-2.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/change-cause: <to be filled in deploy job command>
spec:
  replicas: {{ .Values.prisonVisitsBookingStaff.replicas }}
  revisionHistoryLimit: {{ .Values.prisonVisitsBookingStaff.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: prison-visits-booking-staff
    {{- include "prison-visits-2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: prison-visits-booking-staff
      {{- include "prison-visits-2.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - sh
        - -c
        - bundle exec puma -p 3000 -C ./config/puma_prod.rb --pidfile /tmp/server.pid
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: prison-visits-rds-instance-output
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: elasticache-redis
        - name: NOMIS_USER_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: NOMIS_USER_OAUTH_CLIENT_ID
              name: hmpps-auth-secrets
        - name: NOMIS_USER_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: NOMIS_USER_OAUTH_CLIENT_SECRET
              name: hmpps-auth-secrets
        - name: NOMIS_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: NOMIS_OAUTH_CLIENT_ID
              name: secrets
        - name: NOMIS_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: NOMIS_OAUTH_CLIENT_SECRET
              name: secrets
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "prison-visits-2.fullname" . }}-shared-environment
        - secretRef:
            name: secrets
        image: {{ .Values.prisonVisitsBookingStaff.prisonVisitsBookingStaff.image.repository
          }}:{{ .Values.prisonVisitsBookingStaff.prisonVisitsBookingStaff.image.tag | default
          .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.prisonVisitsBookingStaff.prisonVisitsBookingStaff.imagePullPolicy
          }}
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /ping
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 60
        name: prison-visits-booking-staff
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /ping
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 60
        resources: {{- toYaml .Values.prisonVisitsBookingStaff.prisonVisitsBookingStaff.resources
          | nindent 10 }}
      - command:
        - sh
        - -c
        - bundle exec sidekiq -C config/sidekiq.yml
        env:
        - name: SCRIPT_NAME
          value: {{ quote .Values.prisonVisitsBookingStaff.prisonVisitsBookingStaffSidekiq.env.scriptName
            }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: prison-visits-rds-instance-output
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: elasticache-redis
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "prison-visits-2.fullname" . }}-shared-environment
        - secretRef:
            name: secrets
        image: {{ .Values.prisonVisitsBookingStaff.prisonVisitsBookingStaffSidekiq.image.repository
          }}:{{ .Values.prisonVisitsBookingStaff.prisonVisitsBookingStaffSidekiq.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.prisonVisitsBookingStaff.prisonVisitsBookingStaffSidekiq.imagePullPolicy
          }}
        name: prison-visits-booking-staff-sidekiq
        resources: {}