apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "prison-visits-2.fullname" . }}-load-nomis-slots
  labels:
  {{- include "prison-visits-2.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: {{ .Values.loadNomisSlots.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - sh
            - -c
            - bundle exec rake pvb:load_nomis_slots
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: prison-visits-rds-instance-output
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
            envFrom:
            - configMapRef:
                name: {{ include "prison-visits-2.fullname" . }}-shared-environment
            - secretRef:
                name: secrets
            image: {{ .Values.loadNomisSlots.prisonVisitsBookingStaffLoadNomisSlots.image.repository
              }}:{{ .Values.loadNomisSlots.prisonVisitsBookingStaffLoadNomisSlots.image.tag
              | default .Chart.AppVersion }}
            imagePullPolicy: {{ .Values.loadNomisSlots.prisonVisitsBookingStaffLoadNomisSlots.imagePullPolicy
              }}
            name: prison-visits-booking-staff-load-nomis-slots
            resources: {}
          restartPolicy: OnFailure
  schedule: {{ .Values.loadNomisSlots.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.loadNomisSlots.successfulJobsHistoryLimit
    }}