apiVersion: batch/v1
kind: CronJob
metadata:
  name: load-nomis-slots
spec:
  schedule: "0 0,12 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: prison-visits-booking-staff-load-nomis-slots
            image: "{{ index .Values "generic-service" "image" "repository" }}:{{ index .Values "generic-service" "image" "tag" | default .Chart.AppVersion }}"
            imagePullPolicy: IfNotPresent
            command: ['sh', '-c', "bundle exec rake pvb:load_nomis_slots"]
            envFrom:
              - configMapRef:
                  name: shared-environment
              - secretRef:
                  name: secrets
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: prison-visits-rds-instance-output
                    key: url
          restartPolicy: OnFailure
