apiVersion: batch/v1
kind: Job
metadata:
  name: pvb-staff-migration
  labels:
    app: pvb-staff-migration
spec:
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: prison-visits-staff-migration
          image: "{{ index .Values "generic-service" "image" "repository" }}:{{ index .Values "generic-service" "image" "tag" | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'bundle exec rails db:migrate && bundle exec rails db:seed']
          envFrom:
            - configMapRef:
                name: shared-environment
            - secretRef:
                name: secrets
          env:
            - name: "DISABLE_PROMETHEUS_METRICS"
              value: "true"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prison-visits-rds-instance-output
                  key: url
          resources:
            limits:
              memory: "1Gi"
              cpu: "50m"
            requests:
              memory: "1Gi"
              cpu: "30m"
      restartPolicy: Never
  backoffLimit: 4
