apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "prison-visits-2.fullname" . }}-pvb-staff-migration-dev
  labels:
    app: pvb-staff-migration-dev
  {{- include "prison-visits-2.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.pvbStaffMigrationDev.backoffLimit }}
  completions: {{ .Values.pvbStaffMigrationDev.completions }}
  parallelism: {{ .Values.pvbStaffMigrationDev.parallelism }}
  template:
    spec:
      containers:
      - command:
        - sh
        - -c
        - sleep 5 && bundle exec rails db:migrate && bundle exec rails db:seed
        env:
        - name: DISABLE_PROMETHEUS_METRICS
          value: {{ quote .Values.pvbStaffMigrationDev.prisonVisitsStaffMigration.env.disablePrometheusMetrics
            }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: prison-visits-rds-instance-output
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "prison-visits-2.fullname" . }}-shared-environment
        - secretRef:
            name: secrets
        image: {{ .Values.pvbStaffMigrationDev.prisonVisitsStaffMigration.image.repository
          }}:{{ .Values.pvbStaffMigrationDev.prisonVisitsStaffMigration.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.pvbStaffMigrationDev.prisonVisitsStaffMigration.imagePullPolicy
          }}
        name: prison-visits-staff-migration
        resources: {{- toYaml .Values.pvbStaffMigrationDev.prisonVisitsStaffMigration.resources
          | nindent 10 }}
      restartPolicy: Never