apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prison-visits-2.fullname" . }}-prison-visits-booking-staff
  labels:
  {{- include "prison-visits-2.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: 15s
    port: metrics
  namespaceSelector:
    matchNames:
    - prison-visits-booking-staff-dev
  selector:
    matchLabels:
      app: prison-visits-booking-staff